### ISSUE TITLE
你这里举的例子完全是一样的，例子举的不好哇，柯里化本来就是用到了偏函数，偏函数可以去掉。

### ISSUE THREAD

**Issue by Telanx** [yoyoyohamapi/with-or-without-fp#2]

**Comment by yoyoyohamapi** [comment]
http://stackoverflow.com/questions/218025/what-is-the-difference-between-currying-and-partial-application @Telanx

**Comment by Telanx** [comment]
学习了，感谢大大分享，以前认识不足，理解混淆了

**Comment by yoyoyohamapi** [comment]
@Telanx 我不是大大啊，也在学习，么么哒。我也更新了下例子，之前的例子不好

**Comment by yoyoyohamapi** [comment]
@Telanx ,Elliot 大神的这篇文章也讲了 Curry 和 Partial 的区别：https://medium.com/javascript-scene/curry-or-partial-application-8150044c78b8  curry 化更加严格，在 curry 化的过程中，它总是返回一元函数，只到所有参数接收完毕，才对原函数进行调用。返回一元函数这个性质将帮助到我们的函数组合（compose）
