### ISSUE TITLE
说好的重构代码呢，写了两个就没了

### ISSUE THREAD

**Issue by yexiang1994** [yoyoyohamapi/with-or-without-fp#3]
说好的重构代码呢，写了两个就没了

**Comment by yoyoyohamapi** [comment]
@yexiang1994 
1. 996ICU 中
2. 1 当然也不是借口，工程中我们尝试自己封装 FP utils，尝试 ramda，发现能兼顾易用，好用和学习成本的还是 lodash/fp 分支
3. 发现欠的技术债好多，今年逼一下自己
